-- Seed data for POS System - Default Product List
-- Run this script in Supabase SQL Editor to populate products and prices
-- Last Updated: February 28, 2026

-- Insert all products
INSERT INTO products (name, category) VALUES
-- Biscuits (20 items)
('Bingo', 'Biscuits'),
('Breadstix', 'Biscuits'),
('Combi', 'Biscuits'),
('Cream-O', 'Biscuits'),
('Dowee Donut', 'Biscuits'),
('Eggnog', 'Biscuits'),
('Fita', 'Biscuits'),
('Fudgee Bar', 'Biscuits'),
('Hansel', 'Biscuits'),
('HI-RO', 'Biscuits'),
('Magic Chips', 'Biscuits'),
('Oreo', 'Biscuits'),
('Presto', 'Biscuits'),
('Pretzels', 'Biscuits'),
('Rebisco', 'Biscuits'),
('Richoco', 'Biscuits'),
('Skyflakes', 'Biscuits'),
('Sumo', 'Biscuits'),
('Topps', 'Biscuits'),
('Wafer', 'Biscuits'),
('Calcheese', 'Biscuits'),

-- Bleach (7 items)
('Chlorine', 'Bleach'),
('Zonrox Color (225ml)', 'Bleach'),
('Zonrox Color (95ml)', 'Bleach'),
('Zonrox Orig (100ml)', 'Bleach'),
('Zonrox Orig (1L)', 'Bleach'),
('Zonrox Orig (250ml)', 'Bleach'),
('Zonrox Orig (500ml)', 'Bleach'),

-- Bodycare (21 items)
('Band Aid', 'Bodycare'),
('Bioderm', 'Bodycare'),
('Carefree', 'Bodycare'),
('Charmee Napkin', 'Bodycare'),
('Charmee Pantyliner', 'Bodycare'),
('Colgate', 'Bodycare'),
('Colgate Charcoal', 'Bodycare'),
('Colgate Toothbrush', 'Bodycare'),
('Cotton', 'Bodycare'),
('Fresh Toothbrush', 'Bodycare'),
('Tawas', 'Bodycare'),
('Gentle Cottonbuds', 'Bodycare'),
('Gillette', 'Bodycare'),
('Sister Pantyliner', 'Bodycare'),
('Happy Cotton Buds', 'Bodycare'),
('Kojic', 'Bodycare'),
('Modess', 'Bodycare'),
('Rexona', 'Bodycare'),
('Safeguard', 'Bodycare'),
('Silka', 'Bodycare'),
('Sister Napkin', 'Bodycare'),
('Whisper Napkin', 'Bodycare'),
('Efficascent G', 'Bodycare'),
('Efficasent W', 'Bodycare'),

-- Candies (27 items)
('BarNuts', 'Candies'),
('Candy Burst', 'Candies'),
('Champi', 'Candies'),
('Choco Fun Cup', 'Candies'),
('Chubby', 'Candies'),
('Cloud 9', 'Candies'),
('Fres', 'Candies'),
('Frutos', 'Candies'),
('Jellyace', 'Candies'),
('Judge', 'Candies'),
('SnS Candies', 'Candies'),
('Kopiko', 'Candies'),
('Snowbear', 'Candies'),
('Krim Stix', 'Candies'),
('Lollipop', 'Candies'),
('Maxx', 'Candies'),
('MM''s', 'Candies'),
('Nips', 'Candies'),
('Pochi', 'Candies'),
('Skittles', 'Candies'),
('Tambal2', 'Candies'),
('Tattoo', 'Candies'),
('V-Fresh', 'Candies'),
('Whistle', 'Candies'),
('White Rabbit', 'Candies'),
('BengBeng', 'Candies'),
('Mallows', 'Candies'),
('Polvoron', 'Candies'),

-- Canned (25 items)
('555 Sardines', 'Canned'),
('555 Tuna', 'Canned'),
('Angel Evap', 'Canned'),
('Argentina Beef Loaf', 'Canned'),
('Argentina Corned Beef', 'Canned'),
('Argentina Giniling', 'Canned'),
('Century Tuna', 'Canned'),
('Doreen Condensed', 'Canned'),
('Family Sardines', 'Canned'),
('Purefoods Luncheon Meat (S)', 'Canned'),
('Freska Tuna', 'Canned'),
('Holiday Beef Loaf', 'Canned'),
('Purefoods Luncheon Meat (B)', 'Canned'),
('Holiday Carne Norte', 'Canned'),
('Holiday Corned Beef 150', 'Canned'),
('Holiday Corned Beef 215', 'Canned'),
('Jersey Condensed', 'Canned'),
('Jersey Evap', 'Canned'),
('Mega Sardines', 'Canned'),
('Senorita Sardines', 'Canned'),
('Youngs Town Sardines', 'Canned'),
('Alpine Evap', 'Canned'),
('Fiesta Beef Loaf', 'Canned'),

-- Chips (18 items)
('Cheese Ring', 'Chips'),
('Cheezy', 'Chips'),
('Clover', 'Chips'),
('Cracklings', 'Chips'),
('Fish Cracker', 'Chips'),
('Fishda', 'Chips'),
('Martys', 'Chips'),
('Moby', 'Chips'),
('Nova', 'Chips'),
('Oishi Prawn', 'Chips'),
('Onion Rings', 'Chips'),
('V Cut', 'Chips'),
('Patata', 'Chips'),
('Piattos', 'Chips'),
('Pillows', 'Chips'),
('Rinbee', 'Chips'),
('Spicy Seafood Curls', 'Chips'),
('Sweet Corn', 'Chips'),

-- Cigarettes (10 items)
('Chesterfield Red', 'Cigarettes'),
('Hope', 'Cigarettes'),
('Marlboro Ice Blast', 'Cigarettes'),
('Marlboro Red', 'Cigarettes'),
('Mighty Green', 'Cigarettes'),
('Mighty Red', 'Cigarettes'),
('Winston', 'Cigarettes'),

-- Condiments (27 items)
('Black Beans', 'Condiments'),
('Coco Mama', 'Condiments'),
('Cornstarch', 'Condiments'),
('Crispy Fry', 'Condiments'),
('Del Monte (115ml)', 'Condiments'),
('Del Monte (200ml)', 'Condiments'),
('Ginisa Mix', 'Condiments'),
('Ground Pepper', 'Condiments'),
('Knorr Cubes', 'Condiments'),
('Laurel Leaves', 'Condiments'),
('Spreads', 'Condiments'),
('Magic Sarap', 'Condiments'),
('Oil', 'Condiments'),
('Soy Sauce Sachet', 'Condiments'),
('Oyster Sauce', 'Condiments'),
('Papa Ketchup', 'Condiments'),
('Salt', 'Condiments'),
('Sinigang11', 'Condiments'),
('Soy Sauce (100ml)', 'Condiments'),
('Soy Sauce (200ml)', 'Condiments'),
('Star Anise', 'Condiments'),
('Sugar', 'Condiments'),
('Tasty Boy', 'Condiments'),
('UFC Ketchup', 'Condiments'),
('Vetsin', 'Condiments'),
('Vinegar (100ml)', 'Condiments'),
('Vinegar (200ml)', 'Condiments'),
('Vinegar Sachet', 'Condiments'),
('Whole Pepper', 'Condiments'),

-- Detergent (16 items)
('Cathy', 'Detergent'),
('Champion/Speed/Surf', 'Detergent'),
('Perla', 'Detergent'),
('Ariel', 'Detergent'),
('Surf Powder', 'Detergent'),
('Tide Powder', 'Detergent'),
('Wings', 'Detergent'),
('Surf Fabcon', 'Detergent'),
('Joy Dishwashing', 'Detergent'),
('Downy Fabcon', 'Detergent'),
('Smart Paste/Winner', 'Detergent'),
('Scotch Brite Pad B', 'Detergent'),
('Scotch Brite Pad S', 'Detergent'),
('Scotch Brite Sponge S', 'Detergent'),
('Scotch Brite Stainless', 'Detergent'),
('Scotch Brite Sponge B', 'Detergent'),

-- Fresh (4 items)
('Garlic', 'Fresh'),
('Sili', 'Fresh'),
('Onion', 'Fresh'),
('Egg', 'Fresh'),

-- Grains (7 items)
('Conchita Orange', 'Grains'),
('Ganador', 'Grains'),
('Ivory', 'Grains'),
('Mia', 'Grains'),
('Palawan', 'Grains'),
('Bea', 'Grains'),
('Monggo', 'Grains'),

-- Haircare (11 items)
('Cream Silk', 'Haircare'),
('Gard', 'Haircare'),
('H&S', 'Haircare'),
('Keratin Conditioner', 'Haircare'),
('Keratin Shampoo', 'Haircare'),
('Michael Gel', 'Haircare'),
('Palmolive', 'Haircare'),
('Pantene', 'Haircare'),
('Sunsilk', 'Haircare'),
('Dove', 'Haircare'),
('Hairworks Gel', 'Haircare'),

-- Hot_Cold (2 items)
('Hot Water', 'Hot_Cold'),
('Ice', 'Hot_Cold'),

-- Liquor (8 items)
('Emperador Brandy', 'Liquor'),
('Emperador Light', 'Liquor'),
('Gin Frasco', 'Liquor'),
('Gin Frasquito', 'Liquor'),
('GSM Blue Light Gin', 'Liquor'),
('GSM Blue Mojito', 'Liquor'),
('Kulafu', 'Liquor'),
('Tanduay', 'Liquor'),
('Tanduay Select', 'Liquor'),

-- Medicine (13 items)
('Alaxan FR', 'Medicine'),
('Amoxicillin', 'Medicine'),
('Biogesic', 'Medicine'),
('Diatabs', 'Medicine'),
('Flanax', 'Medicine'),
('Kremil-S', 'Medicine'),
('Lomotil', 'Medicine'),
('Mefenamic', 'Medicine'),
('Neozep', 'Medicine'),
('Rexidol', 'Medicine'),
('Saridon', 'Medicine'),
('Tuseran Forte', 'Medicine'),
('Cetirizine', 'Medicine'),
('Decolgen', 'Medicine'),
('Medicol', 'Medicine'),

-- Miscellaneous (13 items)
('Baygon', 'Miscellaneous'),
('Lighter', 'Miscellaneous'),
('Match', 'Miscellaneous'),
('Rug', 'Miscellaneous'),
('Shoes Glue', 'Miscellaneous'),
('Star Wax', 'Miscellaneous'),
('Plastic Cup', 'Miscellaneous'),
('Scotch Tape', 'Miscellaneous'),
('Butane', 'Miscellaneous'),
('Candle5', 'Miscellaneous'),
('Candle10', 'Miscellaneous'),
('Blade', 'Miscellaneous'),
('Sako5', 'Miscellaneous'),
('Sako10', 'Miscellaneous'),

-- Noodles (9 items)
('Beef Labuyo', 'Noodles'),
('Beef/Chicken', 'Noodles'),
('Bihon', 'Noodles'),
('Cup Noodles', 'Noodles'),
('Misua', 'Noodles'),
('Odong', 'Noodles'),
('Pancit Canton', 'Noodles'),
('Sotanghon', 'Noodles'),
('Cup Sotanghon/Bihon', 'Noodles'),

-- Powdered (11 items)
('Bear Brand', 'Powdered'),
('Blanca Twin', 'Powdered'),
('Coffee Stick', 'Powdered'),
('Energen', 'Powdered'),
('Kopiko Black', 'Powdered'),
('Kopiko Brown', 'Powdered'),
('Milo', 'Powdered'),
('Nescafe Single', 'Powdered'),
('Nescafe Twin', 'Powdered'),
('Nestea', 'Powdered'),
('Tablia', 'Powdered'),
('Tang', 'Powdered'),

-- Refreshment (12 items)
('12oz Mtn Dew', 'Refreshment'),
('8oz (Coke/Sprite/Royal)', 'Refreshment'),
('8oz Mtn Dew', 'Refreshment'),
('C2', 'Refreshment'),
('Chuckie', 'Refreshment'),
('DutchMill', 'Refreshment'),
('Ice Pop', 'Refreshment'),
('Litro (Coke, Royal, Sprite)', 'Refreshment'),
('Mismo', 'Refreshment'),
('Nature''s Spring 500', 'Refreshment'),
('Yakult', 'Refreshment'),
('Zest-O', 'Refreshment');

-- Insert prices with exact values from the data
INSERT INTO prices (product_id, price) VALUES
-- Biscuits
((SELECT id FROM products WHERE name='Bingo' AND category='Biscuits' LIMIT 1), 7.00),
((SELECT id FROM products WHERE name='Breadstix' AND category='Biscuits' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Combi' AND category='Biscuits' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Cream-O' AND category='Biscuits' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Dowee Donut' AND category='Biscuits' LIMIT 1), 11.00),
((SELECT id FROM products WHERE name='Eggnog' AND category='Biscuits' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Fita' AND category='Biscuits' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Fudgee Bar' AND category='Biscuits' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Hansel' AND category='Biscuits' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='HI-RO' AND category='Biscuits' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Magic Chips' AND category='Biscuits' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Oreo' AND category='Biscuits' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Presto' AND category='Biscuits' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Pretzels' AND category='Biscuits' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Rebisco' AND category='Biscuits' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Richoco' AND category='Biscuits' LIMIT 1), 12.00),
((SELECT id FROM products WHERE name='Skyflakes' AND category='Biscuits' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Sumo' AND category='Biscuits' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Topps' AND category='Biscuits' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Wafer' AND category='Biscuits' LIMIT 1), 4.00),
((SELECT id FROM products WHERE name='Calcheese' AND category='Biscuits' LIMIT 1), 15.00),

-- Bleach
((SELECT id FROM products WHERE name='Chlorine' AND category='Bleach' LIMIT 1), 1.00),
((SELECT id FROM products WHERE name='Zonrox Color (225ml)' AND category='Bleach' LIMIT 1), 28.00),
((SELECT id FROM products WHERE name='Zonrox Color (95ml)' AND category='Bleach' LIMIT 1), 15.00),
((SELECT id FROM products WHERE name='Zonrox Orig (100ml)' AND category='Bleach' LIMIT 1), 11.00),
((SELECT id FROM products WHERE name='Zonrox Orig (1L)' AND category='Bleach' LIMIT 1), 45.00),
((SELECT id FROM products WHERE name='Zonrox Orig (250ml)' AND category='Bleach' LIMIT 1), 17.00),
((SELECT id FROM products WHERE name='Zonrox Orig (500ml)' AND category='Bleach' LIMIT 1), 26.00),

-- Bodycare
((SELECT id FROM products WHERE name='Band Aid' AND category='Bodycare' LIMIT 1), 2.00),
((SELECT id FROM products WHERE name='Bioderm' AND category='Bodycare' LIMIT 1), 17.00),
((SELECT id FROM products WHERE name='Carefree' AND category='Bodycare' LIMIT 1), 3.00),
((SELECT id FROM products WHERE name='Charmee Napkin' AND category='Bodycare' LIMIT 1), 4.00),
((SELECT id FROM products WHERE name='Charmee Pantyliner' AND category='Bodycare' LIMIT 1), 2.00),
((SELECT id FROM products WHERE name='Colgate' AND category='Bodycare' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='Colgate Charcoal' AND category='Bodycare' LIMIT 1), 12.00),
((SELECT id FROM products WHERE name='Colgate Toothbrush' AND category='Bodycare' LIMIT 1), 20.00),
((SELECT id FROM products WHERE name='Cotton' AND category='Bodycare' LIMIT 1), 6.00),
((SELECT id FROM products WHERE name='Fresh Toothbrush' AND category='Bodycare' LIMIT 1), 15.00),
((SELECT id FROM products WHERE name='Tawas' AND category='Bodycare' LIMIT 1), 12.00),
((SELECT id FROM products WHERE name='Gentle Cottonbuds' AND category='Bodycare' LIMIT 1), 15.00),
((SELECT id FROM products WHERE name='Gillette' AND category='Bodycare' LIMIT 1), 30.00),
((SELECT id FROM products WHERE name='Sister Pantyliner' AND category='Bodycare' LIMIT 1), 2.00),
((SELECT id FROM products WHERE name='Happy Cotton Buds' AND category='Bodycare' LIMIT 1), 6.00),
((SELECT id FROM products WHERE name='Kojic' AND category='Bodycare' LIMIT 1), 30.00),
((SELECT id FROM products WHERE name='Modess' AND category='Bodycare' LIMIT 1), 6.00),
((SELECT id FROM products WHERE name='Rexona' AND category='Bodycare' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Safeguard' AND category='Bodycare' LIMIT 1), 21.00),
((SELECT id FROM products WHERE name='Silka' AND category='Bodycare' LIMIT 1), 18.00),
((SELECT id FROM products WHERE name='Sister Napkin' AND category='Bodycare' LIMIT 1), 4.00),
((SELECT id FROM products WHERE name='Whisper Napkin' AND category='Bodycare' LIMIT 1), 6.00),
((SELECT id FROM products WHERE name='Efficascent G' AND category='Bodycare' LIMIT 1), 35.00),
((SELECT id FROM products WHERE name='Efficasent W' AND category='Bodycare' LIMIT 1), 40.00),

-- Candies
((SELECT id FROM products WHERE name='BarNuts' AND category='Candies' LIMIT 1), 2.00),
((SELECT id FROM products WHERE name='Candy Burst' AND category='Candies' LIMIT 1), 5.00),
((SELECT id FROM products WHERE name='Champi' AND category='Candies' LIMIT 1), 1.00),
((SELECT id FROM products WHERE name='Choco Fun Cup' AND category='Candies' LIMIT 1), 2.00),
((SELECT id FROM products WHERE name='Chubby' AND category='Candies' LIMIT 1), 2.00),
((SELECT id FROM products WHERE name='Cloud 9' AND category='Candies' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='Fres' AND category='Candies' LIMIT 1), 1.00),
((SELECT id FROM products WHERE name='Frutos' AND category='Candies' LIMIT 1), 1.00),
((SELECT id FROM products WHERE name='Jellyace' AND category='Candies' LIMIT 1), 1.00),
((SELECT id FROM products WHERE name='Judge' AND category='Candies' LIMIT 1), 1.00),
((SELECT id FROM products WHERE name='SnS Candies' AND category='Candies' LIMIT 1), 5.00),
((SELECT id FROM products WHERE name='Kopiko' AND category='Candies' LIMIT 1), 1.00),
((SELECT id FROM products WHERE name='Snowbear' AND category='Candies' LIMIT 1), 1.00),
((SELECT id FROM products WHERE name='Krim Stix' AND category='Candies' LIMIT 1), 2.00),
((SELECT id FROM products WHERE name='Lollipop' AND category='Candies' LIMIT 1), 2.00),
((SELECT id FROM products WHERE name='Maxx' AND category='Candies' LIMIT 1), 1.00),
((SELECT id FROM products WHERE name='MM''s' AND category='Candies' LIMIT 1), 15.00),
((SELECT id FROM products WHERE name='Nips' AND category='Candies' LIMIT 1), 2.00),
((SELECT id FROM products WHERE name='Pochi' AND category='Candies' LIMIT 1), 1.00),
((SELECT id FROM products WHERE name='Skittles' AND category='Candies' LIMIT 1), 15.00),
((SELECT id FROM products WHERE name='Tambal2' AND category='Candies' LIMIT 1), 2.00),
((SELECT id FROM products WHERE name='Tattoo' AND category='Candies' LIMIT 1), 1.00),
((SELECT id FROM products WHERE name='V-Fresh' AND category='Candies' LIMIT 1), 1.00),
((SELECT id FROM products WHERE name='Whistle' AND category='Candies' LIMIT 1), 2.00),
((SELECT id FROM products WHERE name='White Rabbit' AND category='Candies' LIMIT 1), 1.00),
((SELECT id FROM products WHERE name='BengBeng' AND category='Candies' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='Mallows' AND category='Candies' LIMIT 1), 2.00),
((SELECT id FROM products WHERE name='Polvoron' AND category='Candies' LIMIT 1), 2.00),

-- Canned
((SELECT id FROM products WHERE name='555 Sardines' AND category='Canned' LIMIT 1), 27.00),
((SELECT id FROM products WHERE name='555 Tuna' AND category='Canned' LIMIT 1), 32.00),
((SELECT id FROM products WHERE name='Angel Evap' AND category='Canned' LIMIT 1), 35.00),
((SELECT id FROM products WHERE name='Argentina Beef Loaf' AND category='Canned' LIMIT 1), 23.00),
((SELECT id FROM products WHERE name='Argentina Corned Beef' AND category='Canned' LIMIT 1), 40.00),
((SELECT id FROM products WHERE name='Argentina Giniling' AND category='Canned' LIMIT 1), 30.00),
((SELECT id FROM products WHERE name='Century Tuna' AND category='Canned' LIMIT 1), 40.00),
((SELECT id FROM products WHERE name='Doreen Condensed' AND category='Canned' LIMIT 1), 47.00),
((SELECT id FROM products WHERE name='Family Sardines' AND category='Canned' LIMIT 1), 27.00),
((SELECT id FROM products WHERE name='Purefoods Luncheon Meat (S)' AND category='Canned' LIMIT 1), 37.00),
((SELECT id FROM products WHERE name='Freska Tuna' AND category='Canned' LIMIT 1), 30.00),
((SELECT id FROM products WHERE name='Holiday Beef Loaf' AND category='Canned' LIMIT 1), 23.00),
((SELECT id FROM products WHERE name='Purefoods Luncheon Meat (B)' AND category='Canned' LIMIT 1), 90.00),
((SELECT id FROM products WHERE name='Holiday Carne Norte' AND category='Canned' LIMIT 1), 32.00),
((SELECT id FROM products WHERE name='Holiday Corned Beef 150' AND category='Canned' LIMIT 1), 38.00),
((SELECT id FROM products WHERE name='Holiday Corned Beef 215' AND category='Canned' LIMIT 1), 55.00),
((SELECT id FROM products WHERE name='Jersey Condensed' AND category='Canned' LIMIT 1), 45.00),
((SELECT id FROM products WHERE name='Jersey Evap' AND category='Canned' LIMIT 1), 33.00),
((SELECT id FROM products WHERE name='Mega Sardines' AND category='Canned' LIMIT 1), 27.00),
((SELECT id FROM products WHERE name='Senorita Sardines' AND category='Canned' LIMIT 1), 27.00),
((SELECT id FROM products WHERE name='Youngs Town Sardines' AND category='Canned' LIMIT 1), 25.00),
((SELECT id FROM products WHERE name='Alpine Evap' AND category='Canned' LIMIT 1), 45.00),
((SELECT id FROM products WHERE name='Fiesta Beef Loaf' AND category='Canned' LIMIT 1), 25.00),

-- Chips
((SELECT id FROM products WHERE name='Cheese Ring' AND category='Chips' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Cheezy' AND category='Chips' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Clover' AND category='Chips' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Cracklings' AND category='Chips' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Fish Cracker' AND category='Chips' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Fishda' AND category='Chips' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Martys' AND category='Chips' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Moby' AND category='Chips' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Nova' AND category='Chips' LIMIT 1), 18.00),
((SELECT id FROM products WHERE name='Oishi Prawn' AND category='Chips' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Onion Rings' AND category='Chips' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='V Cut' AND category='Chips' LIMIT 1), 18.00),
((SELECT id FROM products WHERE name='Patata' AND category='Chips' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Piattos' AND category='Chips' LIMIT 1), 17.00),
((SELECT id FROM products WHERE name='Pillows' AND category='Chips' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='Rinbee' AND category='Chips' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Spicy Seafood Curls' AND category='Chips' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Sweet Corn' AND category='Chips' LIMIT 1), 9.00),

-- Cigarettes
((SELECT id FROM products WHERE name='Chesterfield Red' AND category='Cigarettes' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Hope' AND category='Cigarettes' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Marlboro Ice Blast' AND category='Cigarettes' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='Marlboro Red' AND category='Cigarettes' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='Mighty Green' AND category='Cigarettes' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='Mighty Red' AND category='Cigarettes' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='Winston' AND category='Cigarettes' LIMIT 1), 11.00),

-- Condiments
((SELECT id FROM products WHERE name='Black Beans' AND category='Condiments' LIMIT 1), 25.00),
((SELECT id FROM products WHERE name='Coco Mama' AND category='Condiments' LIMIT 1), 35.00),
((SELECT id FROM products WHERE name='Cornstarch' AND category='Condiments' LIMIT 1), 3.00),
((SELECT id FROM products WHERE name='Crispy Fry' AND category='Condiments' LIMIT 1), 20.00),
((SELECT id FROM products WHERE name='Del Monte (115ml)' AND category='Condiments' LIMIT 1), 22.00),
((SELECT id FROM products WHERE name='Del Monte (200ml)' AND category='Condiments' LIMIT 1), 27.00),
((SELECT id FROM products WHERE name='Ginisa Mix' AND category='Condiments' LIMIT 1), 5.00),
((SELECT id FROM products WHERE name='Ground Pepper' AND category='Condiments' LIMIT 1), 1.00),
((SELECT id FROM products WHERE name='Knorr Cubes' AND category='Condiments' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Laurel Leaves' AND category='Condiments' LIMIT 1), 1.00),
((SELECT id FROM products WHERE name='Spreads' AND category='Condiments' LIMIT 1), 15.00),
((SELECT id FROM products WHERE name='Magic Sarap' AND category='Condiments' LIMIT 1), 7.00),
((SELECT id FROM products WHERE name='Oil' AND category='Condiments' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='Soy Sauce Sachet' AND category='Condiments' LIMIT 1), 3.00),
((SELECT id FROM products WHERE name='Oyster Sauce' AND category='Condiments' LIMIT 1), 7.00),
((SELECT id FROM products WHERE name='Papa Ketchup' AND category='Condiments' LIMIT 1), 12.00),
((SELECT id FROM products WHERE name='Salt' AND category='Condiments' LIMIT 1), 2.00),
((SELECT id FROM products WHERE name='Sinigang11' AND category='Condiments' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Soy Sauce (100ml)' AND category='Condiments' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Soy Sauce (200ml)' AND category='Condiments' LIMIT 1), 12.00),
((SELECT id FROM products WHERE name='Star Anise' AND category='Condiments' LIMIT 1), 2.00),
((SELECT id FROM products WHERE name='Sugar' AND category='Condiments' LIMIT 1), 2.00),
((SELECT id FROM products WHERE name='Tasty Boy' AND category='Condiments' LIMIT 1), 13.00),
((SELECT id FROM products WHERE name='UFC Ketchup' AND category='Condiments' LIMIT 1), 12.00),
((SELECT id FROM products WHERE name='Vetsin' AND category='Condiments' LIMIT 1), 5.00),
((SELECT id FROM products WHERE name='Vinegar (100ml)' AND category='Condiments' LIMIT 1), 7.00),
((SELECT id FROM products WHERE name='Vinegar (200ml)' AND category='Condiments' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Vinegar Sachet' AND category='Condiments' LIMIT 1), 2.00),
((SELECT id FROM products WHERE name='Whole Pepper' AND category='Condiments' LIMIT 1), 1.00),

-- Detergent
((SELECT id FROM products WHERE name='Cathy' AND category='Detergent' LIMIT 1), 15.00),
((SELECT id FROM products WHERE name='Champion/Speed/Surf' AND category='Detergent' LIMIT 1), 7.00),
((SELECT id FROM products WHERE name='Perla' AND category='Detergent' LIMIT 1), 17.00),
((SELECT id FROM products WHERE name='Ariel' AND category='Detergent' LIMIT 1), 16.00),
((SELECT id FROM products WHERE name='Surf Powder' AND category='Detergent' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Tide Powder' AND category='Detergent' LIMIT 1), 16.00),
((SELECT id FROM products WHERE name='Wings' AND category='Detergent' LIMIT 1), 7.00),
((SELECT id FROM products WHERE name='Surf Fabcon' AND category='Detergent' LIMIT 1), 7.00),
((SELECT id FROM products WHERE name='Joy Dishwashing' AND category='Detergent' LIMIT 1), 7.00),
((SELECT id FROM products WHERE name='Downy Fabcon' AND category='Detergent' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Smart Paste/Winner' AND category='Detergent' LIMIT 1), 27.00),
((SELECT id FROM products WHERE name='Scotch Brite Pad B' AND category='Detergent' LIMIT 1), 20.00),
((SELECT id FROM products WHERE name='Scotch Brite Pad S' AND category='Detergent' LIMIT 1), 13.00),
((SELECT id FROM products WHERE name='Scotch Brite Sponge S' AND category='Detergent' LIMIT 1), 23.00),
((SELECT id FROM products WHERE name='Scotch Brite Stainless' AND category='Detergent' LIMIT 1), 27.00),
((SELECT id FROM products WHERE name='Scotch Brite Sponge B' AND category='Detergent' LIMIT 1), 38.00),

-- Fresh
((SELECT id FROM products WHERE name='Garlic' AND category='Fresh' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Sili' AND category='Fresh' LIMIT 1), 5.00),
((SELECT id FROM products WHERE name='Onion' AND category='Fresh' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='Egg' AND category='Fresh' LIMIT 1), 10.00),

-- Grains
((SELECT id FROM products WHERE name='Conchita Orange' AND category='Grains' LIMIT 1), 65.00),
((SELECT id FROM products WHERE name='Ganador' AND category='Grains' LIMIT 1), 65.00),
((SELECT id FROM products WHERE name='Ivory' AND category='Grains' LIMIT 1), 63.00),
((SELECT id FROM products WHERE name='Mia' AND category='Grains' LIMIT 1), 58.00),
((SELECT id FROM products WHERE name='Palawan' AND category='Grains' LIMIT 1), 55.00),
((SELECT id FROM products WHERE name='Bea' AND category='Grains' LIMIT 1), 60.00),
((SELECT id FROM products WHERE name='Monggo' AND category='Grains' LIMIT 1), 30.00),

-- Haircare
((SELECT id FROM products WHERE name='Cream Silk' AND category='Haircare' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Gard' AND category='Haircare' LIMIT 1), 7.00),
((SELECT id FROM products WHERE name='H&S' AND category='Haircare' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Keratin Conditioner' AND category='Haircare' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Keratin Shampoo' AND category='Haircare' LIMIT 1), 7.00),
((SELECT id FROM products WHERE name='Michael Gel' AND category='Haircare' LIMIT 1), 4.00),
((SELECT id FROM products WHERE name='Palmolive' AND category='Haircare' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Pantene' AND category='Haircare' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Sunsilk' AND category='Haircare' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Dove' AND category='Haircare' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Hairworks Gel' AND category='Haircare' LIMIT 1), 3.00),

-- Hot_Cold
((SELECT id FROM products WHERE name='Hot Water' AND category='Hot_Cold' LIMIT 1), 1.00),
((SELECT id FROM products WHERE name='Ice' AND category='Hot_Cold' LIMIT 1), 4.00),

-- Liquor
((SELECT id FROM products WHERE name='Emperador Brandy' AND category='Liquor' LIMIT 1), 70.00),
((SELECT id FROM products WHERE name='Emperador Light' AND category='Liquor' LIMIT 1), 150.00),
((SELECT id FROM products WHERE name='Gin Frasco' AND category='Liquor' LIMIT 1), 145.00),
((SELECT id FROM products WHERE name='Gin Frasquito' AND category='Liquor' LIMIT 1), 80.00),
((SELECT id FROM products WHERE name='GSM Blue Light Gin' AND category='Liquor' LIMIT 1), 130.00),
((SELECT id FROM products WHERE name='GSM Blue Mojito' AND category='Liquor' LIMIT 1), 150.00),
((SELECT id FROM products WHERE name='Kulafu' AND category='Liquor' LIMIT 1), 50.00),
((SELECT id FROM products WHERE name='Tanduay' AND category='Liquor' LIMIT 1), 80.00),
((SELECT id FROM products WHERE name='Tanduay Select' AND category='Liquor' LIMIT 1), 170.00),

-- Medicine
((SELECT id FROM products WHERE name='Alaxan FR' AND category='Medicine' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='Amoxicillin' AND category='Medicine' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Biogesic' AND category='Medicine' LIMIT 1), 6.00),
((SELECT id FROM products WHERE name='Diatabs' AND category='Medicine' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='Flanax' AND category='Medicine' LIMIT 1), 25.00),
((SELECT id FROM products WHERE name='Kremil-S' AND category='Medicine' LIMIT 1), 11.00),
((SELECT id FROM products WHERE name='Lomotil' AND category='Medicine' LIMIT 1), 17.00),
((SELECT id FROM products WHERE name='Mefenamic' AND category='Medicine' LIMIT 1), 5.00),
((SELECT id FROM products WHERE name='Neozep' AND category='Medicine' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Rexidol' AND category='Medicine' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Saridon' AND category='Medicine' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Tuseran Forte' AND category='Medicine' LIMIT 1), 12.00),
((SELECT id FROM products WHERE name='Cetirizine' AND category='Medicine' LIMIT 1), 5.00),
((SELECT id FROM products WHERE name='Decolgen' AND category='Medicine' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='Medicol' AND category='Medicine' LIMIT 1), 9.00),

-- Miscellaneous
((SELECT id FROM products WHERE name='Baygon' AND category='Miscellaneous' LIMIT 1), 6.00),
((SELECT id FROM products WHERE name='Lighter' AND category='Miscellaneous' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Match' AND category='Miscellaneous' LIMIT 1), 3.00),
((SELECT id FROM products WHERE name='Rug' AND category='Miscellaneous' LIMIT 1), 3.00),
((SELECT id FROM products WHERE name='Shoes Glue' AND category='Miscellaneous' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Star Wax' AND category='Miscellaneous' LIMIT 1), 22.00),
((SELECT id FROM products WHERE name='Plastic Cup' AND category='Miscellaneous' LIMIT 1), 1.00),
((SELECT id FROM products WHERE name='Scotch Tape' AND category='Miscellaneous' LIMIT 1), 6.00),
((SELECT id FROM products WHERE name='Butane' AND category='Miscellaneous' LIMIT 1), 28.00),
((SELECT id FROM products WHERE name='Candle5' AND category='Miscellaneous' LIMIT 1), 5.00),
((SELECT id FROM products WHERE name='Candle10' AND category='Miscellaneous' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='Blade' AND category='Miscellaneous' LIMIT 1), 5.00),
((SELECT id FROM products WHERE name='Sako5' AND category='Miscellaneous' LIMIT 1), 5.00),
((SELECT id FROM products WHERE name='Sako10' AND category='Miscellaneous' LIMIT 1), 10.00),

-- Noodles
((SELECT id FROM products WHERE name='Beef Labuyo' AND category='Noodles' LIMIT 1), 11.00),
((SELECT id FROM products WHERE name='Beef/Chicken' AND category='Noodles' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='Bihon' AND category='Noodles' LIMIT 1), 23.00),
((SELECT id FROM products WHERE name='Cup Noodles' AND category='Noodles' LIMIT 1), 25.00),
((SELECT id FROM products WHERE name='Misua' AND category='Noodles' LIMIT 1), 3.00),
((SELECT id FROM products WHERE name='Odong' AND category='Noodles' LIMIT 1), 4.00),
((SELECT id FROM products WHERE name='Pancit Canton' AND category='Noodles' LIMIT 1), 13.00),
((SELECT id FROM products WHERE name='Sotanghon' AND category='Noodles' LIMIT 1), 15.00),
((SELECT id FROM products WHERE name='Cup Sotanghon/Bihon' AND category='Noodles' LIMIT 1), 23.00),

-- Powdered
((SELECT id FROM products WHERE name='Bear Brand' AND category='Powdered' LIMIT 1), 12.00),
((SELECT id FROM products WHERE name='Blanca Twin' AND category='Powdered' LIMIT 1), 15.00),
((SELECT id FROM products WHERE name='Coffee Stick' AND category='Powdered' LIMIT 1), 4.00),
((SELECT id FROM products WHERE name='Energen' AND category='Powdered' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='Kopiko Black' AND category='Powdered' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Kopiko Brown' AND category='Powdered' LIMIT 1), 8.00),
((SELECT id FROM products WHERE name='Milo' AND category='Powdered' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='Nescafe Single' AND category='Powdered' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Nescafe Twin' AND category='Powdered' LIMIT 1), 15.00),
((SELECT id FROM products WHERE name='Nestea' AND category='Powdered' LIMIT 1), 21.00),
((SELECT id FROM products WHERE name='Tablia' AND category='Powdered' LIMIT 1), 9.00),
((SELECT id FROM products WHERE name='Tang' AND category='Powdered' LIMIT 1), 20.00),

-- Refreshment
((SELECT id FROM products WHERE name='12oz Mtn Dew' AND category='Refreshment' LIMIT 1), 15.00),
((SELECT id FROM products WHERE name='8oz (Coke/Sprite/Royal)' AND category='Refreshment' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='8oz Mtn Dew' AND category='Refreshment' LIMIT 1), 10.00),
((SELECT id FROM products WHERE name='C2' AND category='Refreshment' LIMIT 1), 15.00),
((SELECT id FROM products WHERE name='Chuckie' AND category='Refreshment' LIMIT 1), 15.00),
((SELECT id FROM products WHERE name='DutchMill' AND category='Refreshment' LIMIT 1), 15.00),
((SELECT id FROM products WHERE name='Ice Pop' AND category='Refreshment' LIMIT 1), 5.00),
((SELECT id FROM products WHERE name='Litro (Coke, Royal, Sprite)' AND category='Refreshment' LIMIT 1), 45.00),
((SELECT id FROM products WHERE name='Mismo' AND category='Refreshment' LIMIT 1), 20.00),
((SELECT id FROM products WHERE name='Nature''s Spring 500' AND category='Refreshment' LIMIT 1), 15.00),
((SELECT id FROM products WHERE name='Yakult' AND category='Refreshment' LIMIT 1), 13.00),
((SELECT id FROM products WHERE name='Zest-O' AND category='Refreshment' LIMIT 1), 10.00);
